# Generated by Django 5.2.1 on 2025-06-04 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComparisonReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="Human-readable report identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "user_business",
                    models.JSONField(default=dict, help_text="User's business profile"),
                ),
                (
                    "competitor_businesses",
                    models.JSONField(
                        default=list,
                        help_text="Competitor businesses in this comparison",
                    ),
                ),
                (
                    "ai_comparison_summary",
                    models.TextField(
                        help_text="AI-generated summary of the comparison"
                    ),
                ),
                (
                    "ai_improvement_suggestions",
                    models.JSONField(
                        default=list,
                        help_text="List of AI-generated improvement suggestions",
                    ),
                ),
                (
                    "comparison_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured comparison data used for analysis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "comparison_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_business"], name="comparison__user_bu_41e81a_idx"
                    )
                ],
            },
        ),
    ]
