exclude: |
  (?x)^(
    .*migrations/.*         # Django migration files
    |\.venv/.*              # Python virtual environment
    |venv/.*                # Another common virtualenv name
    |node_modules/.*        # Node.js dependencies
    |dist/.*                # Frontend build output
    |\.nuxt/.*              # Nuxt.js output (if applicable)
    |\.pytest_cache/.*      # Pytest cache
    |\.mypy_cache/.*        # MyPy cache
    |\.eslintcache/.*       # ESLint cache
    |__pycache__/.*         # Python bytecode cache
    |.*\.min\.js            # Minified JS files
    |.*\.min\.css           # Minified CSS files
  )

default_language_version:
  python: python3.12
  node: "22"

repos:
  # General Git hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # TypeScript/Vue linting and formatting. Failed to install node
  # TODO: Add TypeScript/Vue linting and formatting

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.28.0
  #   hooks:
  #     - id: eslint
  #       files: \.(js|ts|vue)$
  #       additional_dependencies:
  #         - eslint@9.28.0
  #         - "@typescript-eslint/eslint-plugin"
  #         - "@typescript-eslint/parser"
  #         - "@vue/eslint-config-typescript"

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       files: \.(js|ts|vue|css|scss|html|json|md)$
