services:
  backend:
    build: ./backend
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    ports:
      - "8000:8000"
    depends_on:
      # - redis
      - db

  frontend:
    build: ./frontend
    # command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
  # redis:
  #   image: redis:8-alpine

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: competitor_insights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
