# Generated by Django 5.2.1 on 2025-06-04 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Business name as it appears in search results",
                        max_length=255,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Business website URL"),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full business address"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Business latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Business longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Business rating",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of ratings",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of business photos",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="Business type", max_length=255
                    ),
                ),
                (
                    "has_hours",
                    models.BooleanField(
                        default=False, help_text="Whether business hours are listed"
                    ),
                ),
                (
                    "has_description",
                    models.BooleanField(
                        default=False,
                        help_text="Whether business description is provided",
                    ),
                ),
                (
                    "has_menu_link",
                    models.BooleanField(
                        default=False,
                        help_text="Whether menu/services link is available",
                    ),
                ),
                (
                    "has_price_level",
                    models.BooleanField(
                        default=False, help_text="Whether price level is provided"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "website"], name="businesses__name_096f1a_idx"
                    )
                ],
            },
        ),
    ]
